#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

usage() {
  cat <<'USAGE'
Usage:
  scripts/colab_orchestrate.sh <start|resume|stop|doctor> [options]

Common options:
  --work-dir PATH           Working directory (default: cwd)
  --state-dir PATH          State directory (default: <work-dir>/.colab_local/runtime)
  --dry-run                 Print actions without invoking UI control / SSH attach
  --no-ssh-attach           Do not open local SSH terminal after start/resume
  --headed                  UI automation in headed mode (default)
  --headless                UI automation in headless mode
  --diag-dir PATH           Diagnostics root dir (default: <state-dir>/diagnostics)
  --browser-channel NAME    Browser channel for Playwright UI control: chromium|chrome (default: chromium)
  --cdp-endpoint URL        Connect to an already-open Chrome via CDP (e.g. http://127.0.0.1:9222)

start options:
  --repo-dir PATH           Local git repo path
  --repo OWNER/REPO         GitHub repo slug
  --ref GIT_REF             Git ref (branch/tag/SHA)
  --notebook-path PATH      Notebook path in repo (.ipynb)
  --exp-id ID               Experiment ID
  --run-id ID               Run ID (optional; autogenerated if omitted)
  --publish-notebook        Run publish_notebook_git.sh before start
  --publish-src PATH        Source local notebook path for publish (default: <repo-dir>/<notebook-path>)

resume options:
  --state PATH              Path to session_state.json
  --run-id ID               Override run_id in state

stop options:
  --state PATH              Path to session_state.json

doctor options:
  (no extra options; runs local preflight checks)

Examples:
  scripts/colab_orchestrate.sh start --repo-dir . --repo owner/repo --ref main \
    --notebook-path notebooks/SSH.ipynb --exp-id exp_001 --dry-run
  scripts/colab_orchestrate.sh resume --state .colab_local/runtime/session_state.json --dry-run
  scripts/colab_orchestrate.sh stop --state .colab_local/runtime/session_state.json --dry-run
  scripts/colab_orchestrate.sh doctor
USAGE
}

log() {
  printf '[colab-orchestrate] %s\n' "$*" >&2
}

err() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

require_arg() {
  local name="$1"
  local value="${2:-}"
  [[ -n "${value// }" ]] || err "missing required argument: ${name}"
}

iso_now() {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

ensure_dir() {
  mkdir -p "$1"
}

json_print() {
  python3 - "$@" <<'PY'
import json,sys
obj = json.loads(sys.argv[1])
print(json.dumps(obj, ensure_ascii=False, indent=2))
PY
}

write_json_file() {
  local path="$1"
  local json_payload="$2"
  python3 - "$path" "$json_payload" <<'PY'
import json,sys,os,tempfile
path=sys.argv[1]
payload=json.loads(sys.argv[2])
os.makedirs(os.path.dirname(path), exist_ok=True)
fd,tmp=tempfile.mkstemp(prefix=".tmp.", suffix=".json", dir=os.path.dirname(path))
with os.fdopen(fd, "w", encoding="utf-8") as f:
    json.dump(payload, f, ensure_ascii=False, indent=2)
    f.write("\n")
os.replace(tmp, path)
PY
}

read_json_file() {
  local path="$1"
  [[ -f "$path" ]] || err "json file not found: $path"
  python3 - "$path" <<'PY'
import json,sys
with open(sys.argv[1], encoding="utf-8") as f:
    print(json.dumps(json.load(f), ensure_ascii=False))
PY
}

json_get() {
  local path="$1"
  local key="$2"
  python3 - "$path" "$key" <<'PY'
import json,sys
with open(sys.argv[1], encoding="utf-8") as f:
    d=json.load(f)
v=d
for k in sys.argv[2].split('.'):
    if isinstance(v, dict) and k in v:
        v=v[k]
    else:
        raise SystemExit(2)
if isinstance(v, (dict, list)):
    import json as _j
    print(_j.dumps(v, ensure_ascii=False))
elif v is None:
    print("")
else:
    print(v)
PY
}

json_merge_file() {
  local path="$1"
  local patch="$2"
  python3 - "$path" "$patch" <<'PY'
import json,sys,os,tempfile
path=sys.argv[1]
patch=json.loads(sys.argv[2])
with open(path, encoding="utf-8") as f:
    data=json.load(f)
data.update(patch)
fd,tmp=tempfile.mkstemp(prefix=".tmp.", suffix=".json", dir=os.path.dirname(path))
with os.fdopen(fd, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write("\n")
os.replace(tmp, path)
PY
}

gen_run_id() {
  printf 'run_%s' "$(date -u +%Y%m%dT%H%M%SZ)"
}

github_colab_url() {
  local repo_slug="$1"
  local ref="$2"
  local notebook_path="$3"
  printf 'https://colab.research.google.com/github/%s/blob/%s/%s' "$repo_slug" "$ref" "$notebook_path"
}

run_publish_notebook() {
  local src_notebook="$1"
  local repo_dir="$2"
  local dest_path="$3"
  local repo_slug="$4"
  local ref_name="$5"
  if [[ -x "${REPO_ROOT}/.opencode/skills/google-workspace-sync/scripts/publish_notebook_git.sh" ]]; then
    local dest_abs="${repo_dir}/${dest_path#/}"
    local cmd=(
      "${REPO_ROOT}/.opencode/skills/google-workspace-sync/scripts/publish_notebook_git.sh"
      --src "$src_notebook"
      --repo-dir "$repo_dir"
      --dest-path "$dest_path"
      --repo "$repo_slug"
      --ref "$ref_name"
    )
    # 既存スクリプトは同一ファイル cp で失敗するため、同一パス時は検証/URL生成のみ行う。
    if [[ "$(realpath "$src_notebook")" == "$(realpath "$dest_abs")" ]]; then
      log "publish source and destination are same file; forcing publish dry-run validation only"
      cmd+=(--dry-run)
    fi
    if [[ "$DRY_RUN" -eq 1 ]]; then
      cmd+=(--dry-run)
    fi
    log "publish_notebook: ${cmd[*]}"
    (cd "$repo_dir" && "${cmd[@]}")
  else
    log "publish_notebook_git.sh not found; skip"
  fi
}

call_playwright_control() {
  local mode="$1"
  local input_json="$2"
  local stub_phase="$3"
  local stub_last_cell="$4"
  local stub_include_ssh="$5"
  local browser_channel="$6"
  local cdp_endpoint="$7"

  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "dry-run: skip colab_control_playwright.ts (${mode})"
    python3 - "$mode" "$input_json" "$stub_phase" "$stub_last_cell" "$stub_include_ssh" <<'PY'
import json,sys,datetime
mode=sys.argv[1]
inp=json.loads(sys.argv[2])
phase=sys.argv[3]
last_cell=sys.argv[4]
include_ssh=sys.argv[5] == "1"
out={
  "ok": True,
  "phase": phase,
  "markers": {},
  "last_success_cell_tag": last_cell,
  "diagnostics_dir": inp.get("diag_dir"),
  "current_url": inp.get("notebook_url", "")
}
if include_ssh:
    out["markers"]["COLAB_SSH_JSON"]={
      "version": 1,
      "hostname": "dry-run.example.invalid",
      "ssh_user": "root",
      "proxy_command": "cloudflared access ssh --hostname %h",
      "ssh_key_path_hint": "~/.ssh/solafune_colab",
      "source_notebook_url": inp.get("notebook_url", ""),
      "generated_at": datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00","Z")
    }
if mode != "stop":
    out["markers"]["TRAIN_STATUS_JSON"]={
      "phase": "training",
      "resume_from": None,
      "run_id": inp.get("run_id")
    }
if mode == "stop":
    out["markers"]["SYNC_STATUS_JSON"]={"phase":"sync_done","uploaded":[]}
print(json.dumps(out, ensure_ascii=False))
PY
    return 0
  fi

  local controller="${SCRIPT_DIR}/colab_control_playwright.ts"
  [[ -f "$controller" ]] || err "controller not found: $controller"
  if ! command -v pnpm >/dev/null 2>&1; then
    err "pnpm not found. setup: devbox shell (if configured) and pnpm install"
  fi
  if [[ ! -f "${REPO_ROOT}/package.json" ]]; then
    err "package.json not found. setup: pnpm install"
  fi
  if [[ ! -d "${REPO_ROOT}/node_modules" ]]; then
    err "node_modules not found. run: pnpm install && pnpm exec playwright install chromium"
  fi
  local input_file="${STATE_DIR}/controller_input_${mode}.json"
  local output_file="${STATE_DIR}/controller_output_${mode}.json"
  printf '%s' "$input_json" > "$input_file"
  local user_data_dir="${STATE_DIR}/playwright-profile"
  local cmd=(pnpm exec tsx "$controller" "$mode" \
    --input-file "$input_file" \
    --output-file "$output_file" \
    --user-data-dir "$user_data_dir" \
    --browser-channel "$browser_channel")
  if [[ -n "${cdp_endpoint:-}" ]]; then
    cmd+=(--cdp-endpoint "$cdp_endpoint")
  fi
  "${cmd[@]}"
  cat "$output_file"
}

save_ssh_connection_from_marker() {
  local marker_json="$1"
  local notebook_url="$2"
  local out_path="$3"
  python3 - "$marker_json" "$notebook_url" "$out_path" <<'PY'
import json,sys,datetime,os,tempfile
marker=json.loads(sys.argv[1])
notebook_url=sys.argv[2]
out_path=sys.argv[3]
d=dict(marker)
d.setdefault("version", 1)
d.setdefault("ssh_user", "root")
d.setdefault("proxy_command", "cloudflared access ssh --hostname %h")
d.setdefault("ssh_key_path_hint", "~/.ssh/solafune_colab")
d.setdefault("source_notebook_url", notebook_url)
d.setdefault("generated_at", datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00","Z"))
if not d.get("ssh_command") and d.get("hostname"):
    d["ssh_command"] = (
        f"ssh -i {d['ssh_key_path_hint']} -o ServerAliveInterval=30 -o ServerAliveCountMax=3 "
        f"-o ProxyCommand=\"{d['proxy_command']}\" {d['ssh_user']}@{d['hostname']}"
    )
os.makedirs(os.path.dirname(out_path), exist_ok=True)
fd,tmp=tempfile.mkstemp(prefix=".tmp.", suffix=".json", dir=os.path.dirname(out_path))
with os.fdopen(fd, "w", encoding="utf-8") as f:
    json.dump(d, f, ensure_ascii=False, indent=2)
    f.write("\n")
os.replace(tmp, out_path)
PY
}

extract_marker_json() {
  local marker_name="$1"
  local input_text="$2"
  local parser="${SCRIPT_DIR}/colab_parse_marker_output.py"
  [[ -f "$parser" ]] || err "marker parser not found: $parser"
  python3 "$parser" --marker "$marker_name" --text "$input_text"
}

ssh_attach_if_needed() {
  local ssh_json="$1"
  if [[ "$NO_SSH_ATTACH" -eq 1 ]]; then
    log "skip SSH attach (--no-ssh-attach)"
    return 0
  fi
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "dry-run: skip SSH attach via colab_open_ssh_wezterm.sh"
    return 0
  fi
  "${SCRIPT_DIR}/colab_open_ssh_wezterm.sh" --json "$ssh_json"
}

# ---- argument parsing ----
[[ $# -gt 0 ]] || { usage; exit 1; }
SUBCOMMAND="$1"
shift

WORK_DIR="$PWD"
STATE_DIR=""
STATE_FILE=""
DRY_RUN=0
NO_SSH_ATTACH=0
HEADED=1
DIAG_DIR=""
STATE_DIR_EXPLICIT=0
BROWSER_CHANNEL="chromium"
CDP_ENDPOINT=""

REPO_DIR=""
REPO_SLUG=""
REPO_REF=""
NOTEBOOK_PATH=""
EXP_ID=""
RUN_ID=""
PUBLISH_NOTEBOOK=0
PUBLISH_SRC_NOTEBOOK=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --work-dir) WORK_DIR="${2:-}"; shift 2 ;;
    --state-dir) STATE_DIR="${2:-}"; STATE_DIR_EXPLICIT=1; shift 2 ;;
    --state) STATE_FILE="${2:-}"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --no-ssh-attach) NO_SSH_ATTACH=1; shift ;;
    --headed) HEADED=1; shift ;;
    --headless) HEADED=0; shift ;;
    --diag-dir) DIAG_DIR="${2:-}"; shift 2 ;;
    --browser-channel) BROWSER_CHANNEL="${2:-}"; shift 2 ;;
    --cdp-endpoint) CDP_ENDPOINT="${2:-}"; shift 2 ;;
    --repo-dir) REPO_DIR="${2:-}"; shift 2 ;;
    --repo) REPO_SLUG="${2:-}"; shift 2 ;;
    --ref) REPO_REF="${2:-}"; shift 2 ;;
    --notebook-path) NOTEBOOK_PATH="${2:-}"; shift 2 ;;
    --exp-id) EXP_ID="${2:-}"; shift 2 ;;
    --run-id) RUN_ID="${2:-}"; shift 2 ;;
    --publish-notebook) PUBLISH_NOTEBOOK=1; shift ;;
    --publish-src) PUBLISH_SRC_NOTEBOOK="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) err "unknown arg: $1" ;;
  esac
done

case "$BROWSER_CHANNEL" in
  chromium|chrome) ;;
  *) err "--browser-channel must be chromium or chrome (got: $BROWSER_CHANNEL)" ;;
esac
if [[ -n "$CDP_ENDPOINT" ]]; then
  [[ "$CDP_ENDPOINT" == http://* || "$CDP_ENDPOINT" == https://* ]] || \
    err "--cdp-endpoint must start with http:// or https:// (got: $CDP_ENDPOINT)"
fi

WORK_DIR="$(cd "$WORK_DIR" && pwd)"
if [[ -z "$STATE_DIR" ]]; then
  STATE_DIR="${WORK_DIR}/.colab_local/runtime"
fi
if [[ -z "$DIAG_DIR" ]]; then
  DIAG_DIR="${STATE_DIR}/diagnostics"
fi
SESSION_STATE_PATH_DEFAULT="${STATE_DIR}/session_state.json"
SSH_JSON_PATH="${STATE_DIR}/ssh_connection.json"

ensure_dir "$STATE_DIR"
ensure_dir "$DIAG_DIR"

case "$SUBCOMMAND" in
  doctor)
    preflight_script="${SCRIPT_DIR}/colab_env_preflight.sh"
    [[ -x "$preflight_script" ]] || err "preflight script not executable: $preflight_script"
    "$preflight_script"
    ;;

  start)
    require_arg --repo-dir "$REPO_DIR"
    require_arg --repo "$REPO_SLUG"
    require_arg --ref "$REPO_REF"
    require_arg --notebook-path "$NOTEBOOK_PATH"
    require_arg --exp-id "$EXP_ID"
    REPO_DIR="$(cd "$REPO_DIR" && pwd)"
    [[ -d "$REPO_DIR" ]] || err "repo-dir not found: $REPO_DIR"
    [[ "$NOTEBOOK_PATH" == *.ipynb ]] || err "--notebook-path must end with .ipynb"
    RUN_ID="${RUN_ID:-$(gen_run_id)}"
    NOTEBOOK_URL="$(github_colab_url "$REPO_SLUG" "$REPO_REF" "$NOTEBOOK_PATH")"
    if [[ -z "$PUBLISH_SRC_NOTEBOOK" ]]; then
      PUBLISH_SRC_NOTEBOOK="${REPO_DIR}/${NOTEBOOK_PATH#/}"
    fi

    if [[ "$PUBLISH_NOTEBOOK" -eq 1 ]]; then
      [[ -f "$PUBLISH_SRC_NOTEBOOK" ]] || err "publish source notebook not found: $PUBLISH_SRC_NOTEBOOK"
      run_publish_notebook "$PUBLISH_SRC_NOTEBOOK" "$REPO_DIR" "$NOTEBOOK_PATH" "$REPO_SLUG" "$REPO_REF"
    fi

    START_INPUT_JSON="$(python3 - <<'PY' "$NOTEBOOK_URL" "$STATE_DIR" "$DIAG_DIR" "$RUN_ID" "$HEADED"
import json,sys
print(json.dumps({
  "notebook_url": sys.argv[1],
  "state_dir": sys.argv[2],
  "diag_dir": sys.argv[3],
  "run_id": sys.argv[4],
  "headed": sys.argv[5] == "1",
  "phase": "start",
  "cell_tags": [
    "AGENT_BOOTSTRAP",
    "AGENT_DRIVE_MOUNT",
    "AGENT_DATA_PREP",
    "AGENT_SSH_START",
    "AGENT_TRAIN_RESUME"
  ]
}, ensure_ascii=False))
PY
)"
    CONTROL_OUT="$(call_playwright_control "start" "$START_INPUT_JSON" "training" "AGENT_TRAIN_RESUME" "1" "$BROWSER_CHANNEL" "$CDP_ENDPOINT")"

    COLAB_SSH_JSON="$(extract_marker_json "COLAB_SSH_JSON" "$CONTROL_OUT")"
    save_ssh_connection_from_marker "$COLAB_SSH_JSON" "$NOTEBOOK_URL" "$SSH_JSON_PATH"

    SESSION_JSON="$(python3 - <<'PY' "$WORK_DIR" "$REPO_DIR" "$REPO_SLUG" "$REPO_REF" "$NOTEBOOK_PATH" "$NOTEBOOK_URL" "$EXP_ID" "$RUN_ID" "$CONTROL_OUT"
import json,sys,datetime
ctrl=json.loads(sys.argv[9])
print(json.dumps({
  "version": 1,
  "phase": ctrl.get("phase", "training"),
  "work_dir": sys.argv[1],
  "repo_dir": sys.argv[2],
  "repo_slug": sys.argv[3],
  "repo_ref": sys.argv[4],
  "notebook_path": sys.argv[5],
  "notebook_url": sys.argv[6],
  "exp_id": sys.argv[7],
  "run_id": sys.argv[8],
  "last_success_cell_tag": ctrl.get("last_success_cell_tag", "AGENT_TRAIN_RESUME"),
  "last_train_phase": ((ctrl.get("markers") or {}).get("TRAIN_STATUS_JSON") or {}).get("phase", "training"),
  "updated_at": datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00","Z")
}, ensure_ascii=False))
PY
)"
    write_json_file "$SESSION_STATE_PATH_DEFAULT" "$SESSION_JSON"
    log "session state written: $SESSION_STATE_PATH_DEFAULT"
    log "ssh connection written: $SSH_JSON_PATH"
    ssh_attach_if_needed "$SSH_JSON_PATH"
    ;;

  resume)
    STATE_FILE="${STATE_FILE:-$SESSION_STATE_PATH_DEFAULT}"
    [[ -f "$STATE_FILE" ]] || err "state file not found: $STATE_FILE"
    if [[ "$STATE_DIR_EXPLICIT" -eq 0 ]]; then
      STATE_DIR="$(cd "$(dirname "$STATE_FILE")" && pwd)"
      DIAG_DIR="${STATE_DIR}/diagnostics"
      SSH_JSON_PATH="${STATE_DIR}/ssh_connection.json"
      ensure_dir "$STATE_DIR"
      ensure_dir "$DIAG_DIR"
    fi
    NOTEBOOK_URL="$(json_get "$STATE_FILE" "notebook_url")" || err "state missing notebook_url"
    REPO_REF_STATE="$(json_get "$STATE_FILE" "repo_ref")" || err "state missing repo_ref"
    EXP_ID_STATE="$(json_get "$STATE_FILE" "exp_id")" || err "state missing exp_id"
    RUN_ID_STATE="$(json_get "$STATE_FILE" "run_id")" || err "state missing run_id"
    RUN_ID="${RUN_ID:-$RUN_ID_STATE}"
    require_arg state.notebook_url "$NOTEBOOK_URL"
    require_arg state.repo_ref "$REPO_REF_STATE"
    require_arg state.exp_id "$EXP_ID_STATE"
    require_arg state.run_id "$RUN_ID"

    RESUME_INPUT_JSON="$(python3 - <<'PY' "$NOTEBOOK_URL" "$STATE_DIR" "$DIAG_DIR" "$RUN_ID" "$HEADED"
import json,sys
print(json.dumps({
  "notebook_url": sys.argv[1],
  "state_dir": sys.argv[2],
  "diag_dir": sys.argv[3],
  "run_id": sys.argv[4],
  "headed": sys.argv[5] == "1",
  "phase": "resume",
  "cell_tags": [
    "AGENT_BOOTSTRAP",
    "AGENT_DRIVE_MOUNT",
    "AGENT_DATA_PREP",
    "AGENT_SSH_START",
    "AGENT_TRAIN_RESUME"
  ]
}, ensure_ascii=False))
PY
)"
    CONTROL_OUT="$(call_playwright_control "resume" "$RESUME_INPUT_JSON" "training" "AGENT_TRAIN_RESUME" "1" "$BROWSER_CHANNEL" "$CDP_ENDPOINT")"
    COLAB_SSH_JSON="$(extract_marker_json "COLAB_SSH_JSON" "$CONTROL_OUT")"
    save_ssh_connection_from_marker "$COLAB_SSH_JSON" "$NOTEBOOK_URL" "$SSH_JSON_PATH"
    json_merge_file "$STATE_FILE" "$(python3 - <<'PY' "$CONTROL_OUT"
import json,sys,datetime
ctrl=json.loads(sys.argv[1])
print(json.dumps({
  "phase": ctrl.get("phase", "training"),
  "last_success_cell_tag": ctrl.get("last_success_cell_tag", "AGENT_TRAIN_RESUME"),
  "last_train_phase": ((ctrl.get("markers") or {}).get("TRAIN_STATUS_JSON") or {}).get("phase", "training"),
  "updated_at": datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00","Z")
}, ensure_ascii=False))
PY
)"
    log "session state updated: $STATE_FILE"
    log "ssh connection written: $SSH_JSON_PATH"
    ssh_attach_if_needed "$SSH_JSON_PATH"
    ;;

  stop)
    STATE_FILE="${STATE_FILE:-$SESSION_STATE_PATH_DEFAULT}"
    [[ -f "$STATE_FILE" ]] || err "state file not found: $STATE_FILE"
    if [[ "$STATE_DIR_EXPLICIT" -eq 0 ]]; then
      STATE_DIR="$(cd "$(dirname "$STATE_FILE")" && pwd)"
      DIAG_DIR="${STATE_DIR}/diagnostics"
      SSH_JSON_PATH="${STATE_DIR}/ssh_connection.json"
      ensure_dir "$STATE_DIR"
      ensure_dir "$DIAG_DIR"
    fi
    NOTEBOOK_URL="$(json_get "$STATE_FILE" "notebook_url")" || err "state missing notebook_url"
    require_arg state.notebook_url "$NOTEBOOK_URL"
    STOP_INPUT_JSON="$(python3 - <<'PY' "$NOTEBOOK_URL" "$STATE_DIR" "$DIAG_DIR" "$HEADED"
import json,sys
print(json.dumps({
  "notebook_url": sys.argv[1],
  "state_dir": sys.argv[2],
  "diag_dir": sys.argv[3],
  "headed": sys.argv[4] == "1",
  "phase": "stop",
  "cell_tags": ["AGENT_SYNC_AND_STOP"]
}, ensure_ascii=False))
PY
)"
    CONTROL_OUT="$(call_playwright_control "stop" "$STOP_INPUT_JSON" "stopped" "AGENT_SYNC_AND_STOP" "0" "$BROWSER_CHANNEL" "$CDP_ENDPOINT")"
    python3 - "$CONTROL_OUT" <<'PY'
import json,sys
d=json.loads(sys.argv[1])
sync=(d.get("markers") or {}).get("SYNC_STATUS_JSON") or {}
if sync.get("phase") != "sync_done":
    raise SystemExit("SYNC_STATUS_JSON.phase is not sync_done")
PY
    json_merge_file "$STATE_FILE" "$(python3 - <<'PY'
import json,datetime
print(json.dumps({
  "phase": "stopped",
  "last_success_cell_tag": "AGENT_SYNC_AND_STOP",
  "updated_at": datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00","Z")
}, ensure_ascii=False))
PY
)"
    log "session state updated: $STATE_FILE"
    ;;

  *)
    usage
    err "unknown subcommand: $SUBCOMMAND"
    ;;
esac
